// ============================================================================
// Amazon FPGA Hardware Development Kit
//
// Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Amazon Software License (the "License"). You may not use
// this file except in compliance with the License. A copy of the License is
// located at
//
//    http://aws.amazon.com/asl/
//
// or in the "license" file accompanying this file. This file is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or
// implied. See the License for the specific language governing permissions and
// limitations under the License.
// ============================================================================

//------------------------------------------------------------------------------
// GENERATED FILE. DO NOT MODIFY!
//------------------------------------------------------------------------------
   output logic          clk_main_a0,
   output logic          rst_main_n,
   output logic          clk_hbm_ref,
   output logic          sh_cl_flr_assert,
   input                 cl_sh_flr_done,
   input        [31:0]   cl_sh_status0,
   input        [31:0]   cl_sh_status1,
   input        [31:0]   cl_sh_status2,
   input        [31:0]   cl_sh_id0,
   input        [31:0]   cl_sh_id1,
   output logic [31:0]   sh_cl_ctl0,
   output logic [31:0]   sh_cl_ctl1,
   output logic [31:0]   sh_cl_ctl2,
   output logic [15:0]   sh_cl_status_vdip,
   input        [15:0]   cl_sh_status_vled,
   output logic [1:0]    sh_cl_pwr_state,
   input                 cl_sh_dma_wr_full,
   input                 cl_sh_dma_rd_full,
   input        [15:0]   cl_sh_pcim_awid,
   input        [63:0]   cl_sh_pcim_awaddr,
   input        [7:0]    cl_sh_pcim_awlen,
   input        [2:0]    cl_sh_pcim_awsize,
   input        [1:0]    cl_sh_pcim_awburst,
   input        [3:0]    cl_sh_pcim_awcache,
   input                 cl_sh_pcim_awlock,
   input        [2:0]    cl_sh_pcim_awprot,
   input        [3:0]    cl_sh_pcim_awqos,
   input        [54:0]   cl_sh_pcim_awuser,
   input                 cl_sh_pcim_awvalid,
   output logic          sh_cl_pcim_awready,
   input        [15:0]   cl_sh_pcim_wid,
   input        [511:0]  cl_sh_pcim_wdata,
   input        [63:0]   cl_sh_pcim_wstrb,
   input                 cl_sh_pcim_wlast,
   input        [63:0]   cl_sh_pcim_wuser,
   input                 cl_sh_pcim_wvalid,
   output logic          sh_cl_pcim_wready,
   output logic [15:0]   sh_cl_pcim_bid,
   output logic [1:0]    sh_cl_pcim_bresp,
   output logic          sh_cl_pcim_bvalid,
   input                 cl_sh_pcim_bready,
   input        [15:0]   cl_sh_pcim_arid,
   input        [63:0]   cl_sh_pcim_araddr,
   input        [7:0]    cl_sh_pcim_arlen,
   input        [2:0]    cl_sh_pcim_arsize,
   input        [1:0]    cl_sh_pcim_arburst,
   input        [3:0]    cl_sh_pcim_arcache,
   input                 cl_sh_pcim_arlock,
   input        [2:0]    cl_sh_pcim_arprot,
   input        [3:0]    cl_sh_pcim_arqos,
   input        [54:0]   cl_sh_pcim_aruser,
   input                 cl_sh_pcim_arvalid,
   output logic          sh_cl_pcim_arready,
   output logic [15:0]   sh_cl_pcim_rid,
   output logic [511:0]  sh_cl_pcim_rdata,
   output logic [1:0]    sh_cl_pcim_rresp,
   output logic          sh_cl_pcim_rlast,
   output logic [63:0]   sh_cl_pcim_ruser,
   output logic          sh_cl_pcim_rvalid,
   input                 cl_sh_pcim_rready,
   output logic [1:0]    cfg_max_payload,
   output logic [2:0]    cfg_max_read_req,
   output logic [7:0]    sh_cl_ddr_stat_addr,
   output logic [31:0]   sh_cl_ddr_stat_wdata,
   output logic          sh_cl_ddr_stat_wr,
   output logic          sh_cl_ddr_stat_rd,
   output logic [2:0]    sh_cl_ddr_stat_user,
   input                 cl_sh_ddr_stat_ack,
   input        [31:0]   cl_sh_ddr_stat_rdata,
   input        [7:0]    cl_sh_ddr_stat_int,
   input        [15:0]   cl_sh_apppf_irq_req,
   output logic [15:0]   sh_cl_apppf_irq_ack,
   output logic [15:0]   sh_cl_dma_pcis_awid,
   output logic [63:0]   sh_cl_dma_pcis_awaddr,
   output logic [7:0]    sh_cl_dma_pcis_awlen,
   output logic [2:0]    sh_cl_dma_pcis_awsize,
   output logic [1:0]    sh_cl_dma_pcis_awburst,
   output logic [3:0]    sh_cl_dma_pcis_awcache,
   output logic          sh_cl_dma_pcis_awlock,
   output logic [2:0]    sh_cl_dma_pcis_awprot,
   output logic [3:0]    sh_cl_dma_pcis_awqos,
   output logic [54:0]   sh_cl_dma_pcis_awuser,
   output logic          sh_cl_dma_pcis_awvalid,
   input                 cl_sh_dma_pcis_awready,
   output logic [15:0]   sh_cl_dma_pcis_wid,
   output logic [511:0]  sh_cl_dma_pcis_wdata,
   output logic [63:0]   sh_cl_dma_pcis_wstrb,
   output logic          sh_cl_dma_pcis_wlast,
   output logic [63:0]   sh_cl_dma_pcis_wuser,
   output logic          sh_cl_dma_pcis_wvalid,
   input                 cl_sh_dma_pcis_wready,
   input        [15:0]   cl_sh_dma_pcis_bid,
   input        [1:0]    cl_sh_dma_pcis_bresp,
   input                 cl_sh_dma_pcis_bvalid,
   output logic          sh_cl_dma_pcis_bready,
   output logic [15:0]   sh_cl_dma_pcis_arid,
   output logic [63:0]   sh_cl_dma_pcis_araddr,
   output logic [7:0]    sh_cl_dma_pcis_arlen,
   output logic [2:0]    sh_cl_dma_pcis_arsize,
   output logic [1:0]    sh_cl_dma_pcis_arburst,
   output logic [3:0]    sh_cl_dma_pcis_arcache,
   output logic          sh_cl_dma_pcis_arlock,
   output logic [2:0]    sh_cl_dma_pcis_arprot,
   output logic [3:0]    sh_cl_dma_pcis_arqos,
   output logic [54:0]   sh_cl_dma_pcis_aruser,
   output logic          sh_cl_dma_pcis_arvalid,
   input                 cl_sh_dma_pcis_arready,
   input        [15:0]   cl_sh_dma_pcis_rid,
   input        [511:0]  cl_sh_dma_pcis_rdata,
   input        [1:0]    cl_sh_dma_pcis_rresp,
   input                 cl_sh_dma_pcis_rlast,
   input        [63:0]   cl_sh_dma_pcis_ruser,
   input                 cl_sh_dma_pcis_rvalid,
   output logic          sh_cl_dma_pcis_rready,
   output logic [31:0]   ocl_cl_awaddr,
   output logic [54:0]   ocl_cl_awuser,
   output logic          ocl_cl_awvalid,
   input                 cl_ocl_awready,
   output logic [31:0]   ocl_cl_wdata,
   output logic [3:0]    ocl_cl_wstrb,
   output logic          ocl_cl_wvalid,
   input                 cl_ocl_wready,
   input        [1:0]    cl_ocl_bresp,
   input                 cl_ocl_bvalid,
   output logic          ocl_cl_bready,
   output logic [31:0]   ocl_cl_araddr,
   output logic [54:0]   ocl_cl_aruser,
   output logic          ocl_cl_arvalid,
   input                 cl_ocl_arready,
   input        [31:0]   cl_ocl_rdata,
   input        [1:0]    cl_ocl_rresp,
   input                 cl_ocl_rvalid,
   output logic          ocl_cl_rready,
   output logic [31:0]   sda_cl_awaddr,
   output logic          sda_cl_awvalid,
   input                 cl_sda_awready,
   output logic [31:0]   sda_cl_wdata,
   output logic [3:0]    sda_cl_wstrb,
   output logic          sda_cl_wvalid,
   input                 cl_sda_wready,
   input        [1:0]    cl_sda_bresp,
   input                 cl_sda_bvalid,
   output logic          sda_cl_bready,
   output logic [31:0]   sda_cl_araddr,
   output logic          sda_cl_arvalid,
   input                 cl_sda_arready,
   input        [31:0]   cl_sda_rdata,
   input        [1:0]    cl_sda_rresp,
   input                 cl_sda_rvalid,
   output logic          sda_cl_rready,
   output logic          drck,
   output logic          shift,
   output logic          tdi,
   output logic          update,
   output logic          sel,
   input                 tdo,
   output logic          tms,
   output logic          tck,
   output logic          runtest,
   output logic          reset,
   output logic          capture,
   output logic          bscanid_en,
   output logic [63:0]   sh_cl_glcount0,
   output logic [63:0]   sh_cl_glcount1,
   output logic          hbm_apb_preset_n_1,
   input        [21:0]   hbm_apb_paddr_1,
   input        [2:0]    hbm_apb_pprot_1,
   input                 hbm_apb_psel_1,
   input                 hbm_apb_penable_1,
   input                 hbm_apb_pwrite_1,
   input        [31:0]   hbm_apb_pwdata_1,
   input        [3:0]    hbm_apb_pstrb_1,
   input                 hbm_apb_pready_1,
   input        [31:0]   hbm_apb_prdata_1,
   input                 hbm_apb_pslverr_1,
   output logic          hbm_apb_preset_n_0,
   input        [21:0]   hbm_apb_paddr_0,
   input        [2:0]    hbm_apb_pprot_0,
   input                 hbm_apb_psel_0,
   input                 hbm_apb_penable_0,
   input                 hbm_apb_pwrite_0,
   input        [31:0]   hbm_apb_pwdata_0,
   input        [3:0]    hbm_apb_pstrb_0,
   input                 hbm_apb_pready_0,
   input        [31:0]   hbm_apb_prdata_0,
   input                 hbm_apb_pslverr_0
